name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: nice_nano_v2
            shield: ferris_left
            keymap: cardio
            artifact_name: ferris_left
          - board: nice_nano_v2
            shield: ferris_right
            keymap: cardio
            artifact_name: ferris_right
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Build
        uses: zmkfirmware/zmk-build-action@0.4.1
        with:
          board: ${{ matrix.board }}
          shield: ${{ matrix.shield }}
          keymap: ${{ matrix.keymap }}
          
      - name: Rename artifact
        run: |
          mv firmware/*.uf2 firmware/${{ matrix.artifact_name }}.uf2
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: firmware/*.uf2